[CmdletBinding(SupportsShouldProcess)]
param([Parameter(Mandatory=$true)][string]$Root)
$resolvedParent=Split-Path -Parent $Root
if(-not(Test-Path -LiteralPath $resolvedParent)){throw "NAS parent unavailable or access denied: $resolvedParent"}
$paths=@("00_START_HERE","01_SOURCE_CODE/Git_Info","01_SOURCE_CODE/Git_Bundles","01_SOURCE_CODE/Source_Snapshots","01_SOURCE_CODE/Release_Archives","02_DATABASE/Daily","02_DATABASE/Weekly","02_DATABASE/Monthly","02_DATABASE/Manual","02_DATABASE/Restore_Test","02_DATABASE/Logs","03_OBJECT_STORAGE/Current_Mirror","03_OBJECT_STORAGE/Weekly_Snapshots","03_OBJECT_STORAGE/Monthly_Archives","03_OBJECT_STORAGE/Manifests","03_OBJECT_STORAGE/Logs","05_COMPANY_ASSETS/Logos","05_COMPANY_ASSETS/Images","05_COMPANY_ASSETS/Videos","05_COMPANY_ASSETS/Forms","05_COMPANY_ASSETS/Templates","05_COMPANY_ASSETS/Legal","06_DOCUMENTATION/Architecture","06_DOCUMENTATION/Development","06_DOCUMENTATION/Admin","06_DOCUMENTATION/Content_Owner","06_DOCUMENTATION/Backup","06_DOCUMENTATION/Restore","06_DOCUMENTATION/Security","06_DOCUMENTATION/Handover","07_AI_KNOWLEDGE/Company_Context","07_AI_KNOWLEDGE/Department_Context","07_AI_KNOWLEDGE/Prompts","07_AI_KNOWLEDGE/Retrieval_Rules","07_AI_KNOWLEDGE/AI_Onboarding","07_AI_KNOWLEDGE/Evaluation","07_AI_KNOWLEDGE/Safety","08_AUDIT_AND_REPORTS/Backup_Reports","08_AUDIT_AND_REPORTS/Search_Reports","08_AUDIT_AND_REPORTS/Unanswered_Queries","08_AUDIT_AND_REPORTS/Content_Review","08_AUDIT_AND_REPORTS/Security_Reports","08_AUDIT_AND_REPORTS/Recovery_Test","09_TEMPORARY/Import_Staging","09_TEMPORARY/Export_Staging","09_TEMPORARY/To_Be_Reviewed")
$departments=@("HR","ACC","IT","RGM_OPERATION","MKT","GRAPHIC","MAINTENANCE","MANAGEMENT","GENERAL");$sub=@("01_ORIGINAL_DOCUMENTS","02_APPROVED","03_ARCHIVED","04_FOR_REVIEW","05_TEMPLATES","06_EXPORTS")
foreach($d in $departments){foreach($s in $sub){$paths+="04_KNOWLEDGE_SOURCE/$d/$s"}}
foreach($path in $paths){$target=Join-Path $Root $path;if(-not(Test-Path -LiteralPath $target)){if($PSCmdlet.ShouldProcess($target,"Create directory")){New-Item -ItemType Directory -Path $target|Out-Null}}}
"Planned/created $($paths.Count) directories. Existing content was not moved or deleted."
